### PR TITLE
Main elements and styling

### PR DESCRIPTION
**Pull request by flpfar**
This branch contains the following parts that compose the project:

- Every HTML content like texts, links, icons, etc.
- Header fixed
- Main contents inside grids
- Footer using flex
- Media queries for different screen sizes
- Appropriate readme file

### CODE REVIEW

**Comment by davidmrtz-dev** [comment]
Pull Request under review by David Elí 👨‍💻

**Comment by davidmrtz-dev** [comment]
### **Status: Changes required.** 🔍 ♻️ 
****
### Hi @flpfar @ezeilo-su . 😄 ✋ 
### You do an amazing job so far.
You correctly follow the implementation requirements to do a descriptive readme, pull request and commits! 🎊 🎉 
No errors or warning on the HTML Validator. ✅ 
### However, we have a couple of issues need to be fixed before moving on  👨‍💻  ⬇️ 

- [x] It contains TWN logo at the top left corner of the row.

How it looks now. ⬇️ 

Screen Shot 2020-03-10 at 8 05 33 PM

The example on which the project is based. ⬇️ 

Screen Shot 2020-03-10 at 8 05 39 PM

### This logo only appears on the large size. ☢️ 

****

- [x] On the large size from the latest news to the footer we must have a space gap on each side of the page.
Example images below. ⬇️ 

How it looks now. ⬇️ 

Screen Shot 2020-03-10 at 8 20 28 PM

The example on which the project is based. ⬇️ 

Screen Shot 2020-03-10 at 8 20 05 PM

****
### Optional.
This is not a project requirement, but it can make your project look more professional and also looks better.

- [x] Hover effect on links.

You can implement a hover effect to change the color of the link when the cursor is over the link. In this case, changes to orange.

Screen Shot 2020-03-10 at 8 14 00 PM

- [x]  Hover effect on header images.
Also, the images can have like a shadow effect when the cursor is over the image, just like the original page.

Screen Shot 2020-03-10 at 8 24 54 PM


****

### **Please kindly make the changes required and submit a new code review once you are ready!** 🙏 

Happy coding! 😄 💻  
If you have any questions or need help, you can message me on slack (@ David Eli Martinez Garcia).

I wish you the best and see you at the top! 🎖

**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Twitter: [@davitomix](https://twitter.com/davitomix007)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

**Comment by flpfar** [comment]
Hi @davitomix!

Thank you for reviewing our project! 
We've made every change required and the suggested ones.

**Review by nikasulo — APPROVED** [review]
# Congratulations! @flpfar and @ezeilo-su :medal_military: 
Your project is really great and as such, you may merge! Please continue through the program with the same energy and your level of attention to detail. I wish you the very best and see you at the top :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
